### ISSUE TITLE
make function for t1 analysis

### ISSUE THREAD

**Issue by halleeshearer** [neuroprismlab/calculate_effeX#5]
start with something like... (-Steph)

mdl(:,:,i) = Regression_fast(ones(n,1),X_condition1(:,i)-X_condition2(:,i), 1);
mdl(:,:,i) = Regression_fast([ones(n,1), mean(motion,2)],X_condition1(:,i)-X_condition2(:,i), 1);
for example, you could consider condition1 is emotion and condition2 is rest

**Comment by SNeuroble** [comment]
Resolved
